/** Declaration file generated by dts-gen */

export = figlet;

declare function figlet(txt: any, options: any, next: any): void;

declare namespace figlet {
    const figFonts: {
    };

    const prototype: {
    };

    function defaults(opts: any): any;

    function fonts(next: any): any;

    function fontsSync(): any;

    function loadFont(name: any, next: any): any;

    function loadFontSync(name: any): any;

    function metadata(fontName: any, next: any): void;

    function parseFont(fontName: any, data: any): any;

    function preloadFonts(fonts: any, next: any, ...args: any[]): any;

    function text(txt: any, options: any, next: any, ...args: any[]): any;

    function textSync(txt: any, options: any): any;

    namespace defaults {
        const prototype: {
        };

    }

    namespace fonts {
        const prototype: {
        };

    }

    namespace fontsSync {
        const prototype: {
        };

    }

    namespace loadFont {
        const prototype: {
        };

    }

    namespace loadFontSync {
        const prototype: {
        };

    }

    namespace metadata {
        const prototype: {
        };

    }

    namespace parseFont {
        const prototype: {
        };

    }

    namespace preloadFonts {
        const prototype: {
        };

    }

    namespace text {
        const prototype: {
        };

    }

    namespace textSync {
        const prototype: {
        };

    }

}

